export default {
	"User Registration Form": "Форма реєстрації користувача",
	"Full name": "Повне ім'я",
	"Email address": "Електронна пошта",
	"Phone number": "Номер телефону",
	"Age confirmation form": "Форма підтвердження віку",
	"Please enter your age": "Будь ласка, введіть ваш вік",
	"Language selection": "Вибір мови",
	"Choose language": "Виберіть мову",
	"English": "Англійська",
	"Ukrainian": "Українська",
	"You must be at least 18 years old": "Вам має бути не менше 18 років",
	"Invalid phone number": "Невірний номер телефону",
	"Welcome to our platform!": "Ласкаво просимо на нашу платформу!",
	"Address information": "Інформація про адресу",
	"Street": "Вулиця",
	"City": "Місто",
	"Postal code": "Поштовий код",
	"Country": "Країна",
	"Profile update form": "Форма оновлення профілю",
	"Username": "Ім'я користувача",
	"Biography": "Біографія",
	"Newsletter subscription": "Підписка на розсилку",
	"Subscribe to newsletter": "Підписатися на розсилку"
}
