export default {
	'User Registration Form': 'User Registration Form',
	'Full name': 'Full name',
	'Email address': 'Email address',
	'Phone number': 'Phone number',
	'Age confirmation form': 'Age confirmation form',
	'Please enter your age': 'Please enter your age',
	'Language selection': 'Language selection',
	'Choose language': 'Choose language',
	English: 'English',
	Ukrainian: 'Ukrainian',
	'You must be at least 18 years old': 'You must be at least 18 years old',
	'Invalid phone number': 'Invalid phone number',
	'Welcome to our platform!': 'Welcome to our platform!',
	'Address information': 'Address information',
	Street: 'Street',
	City: 'City',
	'Postal code': 'Postal code',
	Country: 'Country',
	'Profile update form': 'Profile update form',
	Username: 'Username',
	Biography: 'Biography',
	'Newsletter subscription': 'Newsletter subscription',
	'Subscribe to newsletter': 'Subscribe to newsletter',
}
