export default {
	'User Registration Form': 'User Registration Form',
	'Full name': 'Full name',
	'Email address': 'Email address',
	'Phone number': 'Phone number',
	'Age confirmation form': 'Age confirmation form',
	'Please enter your age': 'Please enter your age',
	'Language selection': 'Language selection',
	'Choose language': 'Choose language',
	English: 'English',
	Ukrainian: 'Ukrainian',
	'You must be at least 18 years old': 'You must be at least 18 years old',
	'Invalid phone number': 'Invalid phone number',
	'Welcome to our platform!': 'Welcome to our platform!',
	'Address information': 'Address information',
	Street: 'Street',
	City: 'City',
	'Postal code': 'Postal code',
	Country: 'Country',
	'Profile update form': 'Profile update form',
	Username: 'Username',
	Biography: 'Biography',
	'Newsletter subscription': 'Newsletter subscription',
	'Subscribe to newsletter': 'Subscribe to newsletter',
	'Selection cancelled. Returning to menu...': 'Selection cancelled. Returning to menu...',
	'Thanks for exploring UI‑CLI demos! 🚀': 'Thanks for exploring UI‑CLI demos! 🚀',
	'Select UI‑CLI demo to run:': 'Select UI‑CLI demo to run:',
	'Demo completed. Returning to menu...': 'Demo completed. Returning to menu...',
	'Basic Logging Demo': 'Basic Logging Demo',
	'Select Prompt Demo': 'Select Prompt Demo',
	'Simple UI‑CLI Demo': 'Simple UI‑CLI Demo',
	'Form Input Demo': 'Form Input Demo',
	'UiMessage Demo': 'UiMessage Demo',
	'Table Filtering Demo': 'Table Filtering Demo',
	'Table Filtering (Instant)': 'Table Filtering (Instant)',
	'Autocomplete Search Demo': 'Autocomplete Search Demo',
	'Long List Scrolling Demo': 'Long List Scrolling Demo',
	'Advanced Form Demo': 'Advanced Form Demo',
	'New UI Components (Progress, Spinner, etc)': 'New UI Components (Progress, Spinner, etc)',
	'Toggle Demo': 'Toggle Demo',
	'Slider Demo': 'Slider Demo',
	'ProgressBar Demo': 'ProgressBar Demo',
	'Spinner Demo': 'Spinner Demo',
	'Date & Time': 'Date & Time',
	'DateTime Picker Demo': 'DateTime Picker Demo',
	'Scenario 1: Select a Date': 'Scenario 1: Select a Date',
	'Pick a date:': 'Pick a date:',
	'Scenario 2: Select Time (HH:mm)': 'Scenario 2: Select Time (HH:mm)',
	'Pick a time:': 'Pick a time:',
	'Scenario 3: Full Date & Time': 'Scenario 3: Full Date & Time',
	'Pick full date and time:': 'Pick full date and time:',
	'You selected time:': 'You selected time:',
	'← Exit': '← Exit',
	yes: 'yes',
	no: 'no',
	'Pick a colour': 'Pick a colour',
	Red: 'Red',
	Green: 'Green',
	Blue: 'Blue',
	'Select Volume': 'Select Volume',
	'Volume set to:': 'Volume set to:',
	'Loading heavy data...': 'Loading heavy data...',
	'Processing items': 'Processing items',
	'Selected:': 'Selected:',
	'You selected:': 'You selected:',
	'Logger initialized': 'Logger initialized',
	'This demo simply logs messages': 'This demo simply logs messages',
	'Starting server on port 3033': 'Starting server on port 3033',
	'Dumping build to ./dist': 'Dumping build to ./dist',
	'Form Demo – Using Custom Form Class': 'Form Demo – Using Custom Form Class',
	'Filling user form... (uses predefined sequence if set)':
		'Filling user form... (uses predefined sequence if set)',
	'Unique user name': 'Unique user name',
	'User age': 'User age',
	'Favorite color': 'Favorite color',
	'Invalid username (alphanumeric only)': 'Invalid username (alphanumeric only)',
	'Age must be 18 or older': 'Age must be 18 or older',
	'Invalid color': 'Invalid color',
	'Form error:': 'Form error:',
	'Form completed successfully!': 'Form completed successfully!',
	'User:': 'User:',
	'Age:': 'Age:',
	'Color:': 'Color:',
	'UiMessage Demo – Schema‑driven Form': 'UiMessage Demo – Schema‑driven Form',
	'Form completed!': 'Form completed!',
	'Result →': 'Result →',
	'Interactive Table Demo': 'Interactive Table Demo',
	'Search (highlighting matches):': 'Search (highlighting matches):',
	'Results:': 'Results:',
	'Instant Filtering Table': 'Instant Filtering Table',
	'Autocomplete Demo': 'Autocomplete Demo',
	'Choose a country:': 'Choose a country:',
	'selected:': 'selected:',
	'Long List Demo (Scroll to see more)': 'Long List Demo (Scroll to see more)',
	'Pick an item': 'Pick an item',
	'Generating 100 items...': 'Generating 100 items...',
	'Only 10 will be visible at once.': 'Only 10 will be visible at once.',
	Option: 'Option',
	'Selected item ID:': 'Selected item ID:',
	'tree.empty': '(empty)',
	'tree.loading': '(loading...)',
	'tree.help.single': '(Use arrow keys to navigate, Enter to confirm)',
	'tree.help.multi': '(Use arrow keys to navigate, Space to select, Enter to confirm)',
	'tree.selected': 'selected',
	'Full path:': 'Full path:',
	BREADCRUMBS: 'BREADCRUMBS',
	Home: 'Home',
	NanoWeb: 'NanoWeb',
	'UI-CLI': 'UI-CLI',
	Demos: 'Demos',
	Users: 'Users',
	Admin: 'Admin',
	Settings: 'Settings',
	TABS: 'TABS',
	General: 'General',
	Profile: 'Profile',
	Security: 'Security',
	Notifications: 'Notifications',
	'STEPS (WIZARD)': 'STEPS (WIZARD)',
	Cart: 'Cart',
	Shipping: 'Shipping',
	Payment: 'Payment',
	Review: 'Review',
	BADGES: 'BADGES',
	Error: 'Error',
	TOASTS: 'TOASTS',
	ALERTS: 'ALERTS',
	Info: 'Info',
	Warning: 'Warning',
	Online: 'Online',
	Offline: 'Offline',
	Green: 'Green',
	Blue: 'Blue',
	Red: 'Red',
	'table.filter_prompt': 'Filter table',
	'Format must be:': 'Format must be:',
	yes: 'Yes',
	no: 'No',
	// V2 Components
	'V2 Components': 'V2 Components',
	'This demo uses declarative functional components via render().':
		'This demo uses declarative functional components via render().',
	'New Architecture': 'New Architecture',
	'What is your name?': 'What is your name?',
	Welcome: 'Welcome',
	'Choose your role:': 'Choose your role:',
	'Years of experience:': 'Years of experience:',
	'Are you ready to build?': 'Are you ready to build?',
	'Profile Created': 'Profile Created',
	User: 'User',
	Role: 'Role',
	Exp: 'Exp',
	years: 'years',
	Ready: 'Ready',
	Yes: 'Yes',
	No: 'No',
	Developer: 'Developer',
	Designer: 'Designer',
	Manager: 'Manager',
	Production: 'Production',
	Staging: 'Staging',
	Development: 'Development',
	Logging: 'Logging',
	Caching: 'Caching',
	Metrics: 'Metrics',
	USA: 'USA',
	France: 'France',
	Germany: 'Germany',
	Japan: 'Japan',
	Ukraine: 'Ukraine',
	'--- V2 Components Showcase ---': '--- V2 Components Showcase ---',
	'V2 Architecture Showcase': 'V2 Architecture Showcase',
	'Demonstrating 100% of functional components in the new renderer engine.':
		'Demonstrating 100% of functional components in the new renderer engine.',
	MODULAR: 'MODULAR',
	'DEPENDENCY-FREE': 'DEPENDENCY-FREE',
	'Engine initialized': 'Engine initialized',
	'Snapshot mode active': 'Snapshot mode active',
	'Initializing components...': 'Initializing components...',
	'Checking system state...': 'Checking system state...',
	'System Ready': 'System Ready',
	'Navigation Views:': 'Navigation Views:',
	'Data Views (Static Table):': 'Data Views (Static Table):',
	'Component Registry': 'Component Registry',
	'Interactive Phase 1: Identity': 'Interactive Phase 1: Identity',
	'Enter username:': 'Enter username:',
	'Enter secret key:': 'Enter secret key:',
	'Enable telemetry:': 'Enable telemetry:',
	'Confirm deployment?': 'Confirm deployment?',
	'Choose language / Оберіть мову:': 'Choose language / Оберіть мову:',
	'Interactive Phase 2: Configuration': 'Interactive Phase 2: Configuration',
	'Select environment:': 'Select environment:',
	'Select features to enable:': 'Select features to enable:',
	'Enter country:': 'Enter country:',
	'Interactive Phase 3: Parameters': 'Interactive Phase 3: Parameters',
	'CPU Limit (%)': 'CPU Limit (%)',
	'Contact Phone:': 'Contact Phone:',
	'Deploy Date:': 'Deploy Date:',
	'Interactive Phase 4: File System': 'Interactive Phase 4: File System',
	'Select deploy target:': 'Select deploy target:',
	'Setup Complete': 'Setup Complete',
	Env: 'Env',
	CPU: 'CPU',
	Target: 'Target',
	Features: 'Features',
	'Press any key to finish demonstration...': 'Press any key to finish demonstration...',
	// InputAdapter system messages
	'Choose (number): ': 'Choose (number): ',
	'Field is required.': 'Field is required.',
	more: 'more',
	Instructions: 'Instructions',
	'Highlight option': 'Highlight option',
	'Toggle selection': 'Toggle selection',
	'Toggle all': 'Toggle all',
	'Complete answer': 'Complete answer',
	'validate.error': 'Validation error',
	Select: 'Select',
	'Instant Filter': 'Instant Filter',
	'hint.multiselect': '(Space to select. Enter to submit)',
	'hint.select': '(Use arrow keys. Return to submit)',
	'Full Showcase': 'Full Showcase',
	'Select V2 Demo Scenario': 'Select V2 Demo Scenario',
	filter: 'Filter',
	none: 'none',
	// Sortable
	'hint.sortable': '(↑/↓ to navigate, Space to grab, Enter to confirm)',
	'↑/↓': '↑/↓',
	Navigate: 'Navigate',
	Grab: 'Grab',
	Confirm: 'Confirm',
	// Sortable demo
	Sortable: 'Sortable',
	'Sortable Demo': 'Sortable Demo',
	'Reorder items using ↑/↓ to navigate, Space to grab, then ↑/↓ to move.':
		'Reorder items using ↑/↓ to navigate, Space to grab, then ↑/↓ to move.',
	'Scenario 1: Reorder priorities': 'Scenario 1: Reorder priorities',
	'Set priority order:': 'Set priority order:',
	Critical: 'Critical',
	High: 'High',
	Medium: 'Medium',
	Low: 'Low',
	'Final order:': 'Final order:',
	'Object Form': 'Object Form',
	'Save and exit': 'Save and exit',
	'Cancel changes': 'Cancel changes',
	'Edit:': 'Edit:',
	'Select field to edit:': 'Select field to edit:',
}
