export default {
	'User Registration Form': 'User Registration Form',
	'Full name': 'Full name',
	'Email address': 'Email address',
	'Phone number': 'Phone number',
	'Age confirmation form': 'Age confirmation form',
	'Please enter your age': 'Please enter your age',
	'Language selection': 'Language selection',
	'Choose language': 'Choose language',
	English: 'English',
	Ukrainian: 'Ukrainian',
	'You must be at least 18 years old': 'You must be at least 18 years old',
	'Invalid phone number': 'Invalid phone number',
	'Welcome to our platform!': 'Welcome to our platform!',
	'Address information': 'Address information',
	Street: 'Street',
	City: 'City',
	'Postal code': 'Postal code',
	Country: 'Country',
	'Profile update form': 'Profile update form',
	Username: 'Username',
	Biography: 'Biography',
	'Newsletter subscription': 'Newsletter subscription',
	'Subscribe to newsletter': 'Subscribe to newsletter',
	'Selection cancelled. Returning to menu...': 'Selection cancelled. Returning to menu...',
	'Thanks for exploring UI‑CLI demos! 🚀': 'Thanks for exploring UI‑CLI demos! 🚀',
	'Select UI‑CLI demo to run:': 'Select UI‑CLI demo to run:',
	'Demo completed. Returning to menu...': 'Demo completed. Returning to menu...',
	'Basic Logging Demo': 'Basic Logging Demo',
	'Select Prompt Demo': 'Select Prompt Demo',
	'Simple UI‑CLI Demo': 'Simple UI‑CLI Demo',
	'Form Input Demo': 'Form Input Demo',
	'UiMessage Demo': 'UiMessage Demo',
	'Table Filtering Demo': 'Table Filtering Demo',
	'Table Filtering (Instant)': 'Table Filtering (Instant)',
	'Autocomplete Search Demo': 'Autocomplete Search Demo',
	'Long List Scrolling Demo': 'Long List Scrolling Demo',
	'Advanced Form Demo': 'Advanced Form Demo',
	'New UI Components (Progress, Spinner, etc)': 'New UI Components (Progress, Spinner, etc)',
	'Toggle Demo': 'Toggle Demo',
	'Slider Demo': 'Slider Demo',
	'ProgressBar Demo': 'ProgressBar Demo',
	'Spinner Demo': 'Spinner Demo',
	'Date & Time': 'Date & Time',
	'DateTime Picker Demo': 'DateTime Picker Demo',
	'Scenario 1: Select a Date': 'Scenario 1: Select a Date',
	'Pick a date:': 'Pick a date:',
	'Scenario 2: Select Time (HH:mm)': 'Scenario 2: Select Time (HH:mm)',
	'Pick a time:': 'Pick a time:',
	'Scenario 3: Full Date & Time': 'Scenario 3: Full Date & Time',
	'Pick full date and time:': 'Pick full date and time:',
	'You selected time:': 'You selected time:',
	'← Exit': '← Exit',
	yes: 'yes',
	no: 'no',
	'Pick a colour': 'Pick a colour',
	Red: 'Red',
	Green: 'Green',
	Blue: 'Blue',
	'Select Volume': 'Select Volume',
	'Volume set to:': 'Volume set to:',
	'Loading heavy data...': 'Loading heavy data...',
	'Processing items': 'Processing items',
	'Selected:': 'Selected:',
	'You selected:': 'You selected:',
	'Logger initialized': 'Logger initialized',
	'This demo simply logs messages': 'This demo simply logs messages',
	'Starting server on port 3033': 'Starting server on port 3033',
	'Dumping build to ./dist': 'Dumping build to ./dist',
	'Form Demo – Using Custom Form Class': 'Form Demo – Using Custom Form Class',
	'Filling user form... (uses predefined sequence if set)': 'Filling user form... (uses predefined sequence if set)',
	'Unique user name': 'Unique user name',
	'User age': 'User age',
	'Favorite color': 'Favorite color',
	'Invalid username (alphanumeric only)': 'Invalid username (alphanumeric only)',
	'Age must be 18 or older': 'Age must be 18 or older',
	'Invalid color': 'Invalid color',
	'Form error:': 'Form error:',
	'Form completed successfully!': 'Form completed successfully!',
	'User:': 'User:',
	'Age:': 'Age:',
	'Color:': 'Color:',
	'UiMessage Demo – Schema‑driven Form': 'UiMessage Demo – Schema‑driven Form',
	'Form completed!': 'Form completed!',
	'Result →': 'Result →',
	'Interactive Table Demo': 'Interactive Table Demo',
	'Search (highlighting matches):': 'Search (highlighting matches):',
	'Results:': 'Results:',
	'Instant Filtering Table': 'Instant Filtering Table',
	'Autocomplete Demo': 'Autocomplete Demo',
	'Choose a country:': 'Choose a country:',
	'selected:': 'selected:',
	'Long List Demo (Scroll to see more)': 'Long List Demo (Scroll to see more)',
	'Pick an item': 'Pick an item',
	'Generating 100 items...': 'Generating 100 items...',
	'Only 10 will be visible at once.': 'Only 10 will be visible at once.',
	Option: 'Option',
	'Selected item ID:': 'Selected item ID:',
	'tree.empty': '(empty)',
	'tree.loading': '(loading...)',
	'tree.help.single': '(Use arrow keys to navigate, Enter to confirm)',
	'tree.help.multi': '(Use arrow keys to navigate, Space to select, Enter to confirm)',
	'tree.selected': 'selected',
	'Full path:': 'Full path:',
	BREADCRUMBS: 'BREADCRUMBS',
	Home: 'Home',
	NanoWeb: 'NanoWeb',
	'UI-CLI': 'UI-CLI',
	Demos: 'Demos',
	Users: 'Users',
	Admin: 'Admin',
	Settings: 'Settings',
	TABS: 'TABS',
	General: 'General',
	Profile: 'Profile',
	Security: 'Security',
	Notifications: 'Notifications',
	'STEPS (WIZARD)': 'STEPS (WIZARD)',
	Cart: 'Cart',
	Shipping: 'Shipping',
	Payment: 'Payment',
	Review: 'Review',
	BADGES: 'BADGES',
	'Error': 'Error',
	TOASTS: 'TOASTS',
	ALERTS: 'ALERTS',
	Info: 'Info',
	Warning: 'Warning',
	Online: 'Online',
	Offline: 'Offline',
	'Green': 'Green',
	'Blue': 'Blue',
	'Red': 'Red'
}
