export default {
	'User Registration Form': 'Форма реєстрації користувача',
	'Full name': "Повне ім'я",
	'Email address': 'Електронна пошта',
	'Phone number': 'Номер телефону',
	'Age confirmation form': 'Форма підтвердження віку',
	'Please enter your age': 'Будь ласка, введіть ваш вік',
	'Language selection': 'Вибір мови',
	'Choose language': 'Виберіть мову',
	English: 'Англійська',
	Ukrainian: 'Українська',
	'You must be at least 18 years old': 'Вам має бути не менше 18 років',
	'Invalid phone number': 'Невірний номер телефону',
	'Welcome to our platform!': 'Ласкаво просимо на нашу платформу!',
	'Address information': 'Інформація про адресу',
	Street: 'Вулиця',
	City: 'Місто',
	'Postal code': 'Поштовий код',
	Country: 'Країна',
	'First name': "Ім'я",
	'Last name': 'Прізвище',
	'First name (Latin)': "Ім'я (латиницею)",
	'Last name (Latin)': 'Прізвище (латиницею)',
	'Contact email': 'Контактний email',
	'Contact phone': 'Контактний телефон',
	'Education level': 'Рівень освіти',
	'Scientific / academic degree': 'Науковий ступінь',
	'Current position / title': 'Посада',
	'Workplace / organization': 'Місце роботи / Організація',
	'Requested membership level': 'Бажаний рівень членства',
	'Application status': 'Статус заявки',
	'Submission date': 'Дата подачі',
	'Approved by (Member ID)': 'Затверджено користувачем (ID)',
	'Profile update form': 'Форма оновлення профілю',
	RegistrationModel: 'Форма реєстрації',
	VtoropavModel: 'Оновлення статусу учасників',
	ProtocolModel: 'Протокол засідання (Рада)',
	LoginModel: 'Форма авторизації',
	CabinetModel: 'Кабінет користувача',
	Master: 'Магістр / Спеціаліст',
	Bachelor: 'Бакалавр',
	PhD: 'Доктор філософії',
	Professor: 'Професор',
	None: 'Відсутній',
	'Candidate of Sciences': 'Кандидат наук',
	'Doctor of Sciences': 'Доктор наук',
	pending: 'В очікуванні',
	approved: 'Схвалено',
	rejected: 'Відхилено',
	Username: "Ім'я користувача",
	Biography: 'Біографія',
	'Newsletter subscription': 'Підписка на розсилку',
	'Subscribe to newsletter': 'Підписатися на розсилку',
	'Selection cancelled. Returning to menu...': 'Вибір скасовано. Повернення до меню...',
	'Thanks for exploring UI‑CLI demos! 🚀': 'Дякуємо, що спробували UI‑CLI! 🚀',
	'Select UI‑CLI demo to run:': 'Виберіть демо UI‑CLI:',
	'Demo completed. Returning to menu...': 'Демо завершено. Повернення до меню...',
	'Select demo to run:': 'Виберіть демо для запуску:',
	'Error occurred. Returning to menu...': 'Сталася помилка. Повернення до меню...',
	'Basic Logging Demo': 'Логування',
	'Basic Logging': 'Базове логування',
	'Select Prompt Demo': 'Вибір зі списку',
	'Select Prompt': 'Вибір зі списку',
	'Simple UI‑CLI Demo': 'Просте UI‑CLI демо',
	'Simple Demo': 'Просте демо',
	'Form Input Demo': 'Ввід через форму',
	'Form Input': 'Ввід через форму',
	'UiMessage Demo': 'Робота з повідомленнями',
	UiMessage: 'Повідомлення',
	'Table Filtering Demo': 'Таблиця з фільтрацією',
	'Table Filtering': 'Фільтрація таблиці',
	'Table Filtering (Instant)': 'Миттєва фільтрація таблиці',
	'Instant Table': 'Миттєва таблиця',
	'Autocomplete Demo': 'Автодоповнення',
	Autocomplete: 'Автодоповнення',
	'Long List Scrolling Demo': 'Прокрутка великих списків',
	'Long List': 'Великий список',
	'Advanced Form Demo': 'Розширена форма',
	'Advanced Form': 'Розширена форма',
	'New UI Components (Progress, Spinner, etc)': 'Нові компоненти (Progress, Spinner тощо)',
	'Toggle Demo': 'Демо перемикача',
	Toggle: 'Перемикач',
	'Slider Demo': 'Демо повзунка',
	Slider: 'Повзунок',
	'ProgressBar Demo': 'Демо прогресу',
	ProgressBar: 'Прогрес',
	'Spinner Demo': 'Демо спінера',
	Spinner: 'Спінер',
	'Date & Time': 'Дата та час',
	'DateTime Picker Demo': 'Демо вибору дати та часу',
	'Scenario 1: Select a Date': 'Сценарій 1: Вибір дати',
	'Pick a date:': 'Оберіть дату:',
	'Scenario 2: Select Time (HH:mm)': 'Сценарій 2: Вибір часу (ГГ:хв)',
	'Pick a time:': 'Оберіть час:',
	'Scenario 3: Full Date & Time': 'Сценарій 3: Повна дата та час',
	'Pick full date and time:': 'Оберіть повну дату та час:',
	'You selected time:': 'Ви обрали час:',
	'← Exit': '← Вихід',
	Exit: 'Вихід',
	yes: 'так',
	no: 'ні',
	'Pick a colour': 'Оберіть колір',
	Red: 'Червоний',
	Green: 'Зелений',
	Blue: 'Синій',
	'Select Volume': 'Оберіть гучність',
	'Volume set to:': 'Гучність встановлено:',
	'Loading heavy data...': 'Завантаження важких даних...',
	'Processing items': 'Обробка елементів',
	'You selected:': 'Ви обрали:',
	'Logger initialized': 'Логгер ініціалізовано',
	'This demo simply logs messages': 'Це демо просто виводить лог-повідомлення',
	'Starting server on port 3033': 'Запуск сервера на порту 3033',
	'Dumping build to ./dist': 'Дамп збірки в ./dist',
	'Form Demo – Using Custom Form Class': 'Демо форми – Використання кастомного класу форми',
	'Filling user form... (uses predefined sequence if set)':
		'Заповнення форми користувача... (використовує зумовлену послідовність)',
	'Unique user name': "Унікальне ім'я користувача",
	'User age': 'Вік користувача',
	'Favorite color': 'Улюблений колір',
	'Invalid username (alphanumeric only)': "Некоректне ім'я (тільки латиниця та цифри)",
	'Age must be 18 or older': 'Вік має бути 18 років або більше',
	'Invalid color': 'Некоректний колір',
	'Form error:': 'Помилка форми:',
	'Form completed successfully!': 'Форму успішно заповнено!',
	'User:': 'Користувач:',
	'Age:': 'Вік:',
	'Color:': 'Колір:',
	'UiMessage Demo – Schema‑driven Form': 'UiMessage Демо – Форма за схемою',
	'Form completed!': 'Форму заповнено!',
	Result: 'Результат',
	'Result →': 'Результат →',
	'Interactive Table Demo': 'Демо інтерактивної таблиці',
	'Search (highlighting matches):': 'Пошук (підсвічування збігів):',
	'Results:': 'Результати:',
	'Instant Filtering Table': 'Таблиця з миттєвою фільтрацією',
	'Autocomplete Demo': 'Автодоповнення (Autocomplete)',
	'Choose a country:': 'Оберіть країну:',
	'selected:': 'обрано:',
	'Long List Demo (Scroll to see more)': 'Демо довгого списку (гортайте для перегляду)',
	'Pick an item': 'Оберіть елемент',
	'Username is required (supports Latin, Cyrillic, etc.)':
		"Ім'я користувача обов'язкове (підтримує латиницю, кирилицю тощо)",
	'User name': "Ім'я користувача",
	'Username is required (supports any language)': "Ім'я користувача обов'язкове (будь-якою мовою)",
	'Choose (number)': 'Виберіть (номер)',
	'Choose (number): ': 'Виберіть (номер): ',
	Invalid: 'Некоректно:',
	'Field is required.': "Поле обов'язкове для заповнення.",
	'Generating 100 items...': 'Генерація 100 елементів...',
	'Only 10 will be visible at once.': 'Лише 10 буде видно одночасно.',
	Option: 'Опція',
	'Selected item ID:': 'ID обраного елемента:',
	// Autocomplete demo
	'Tip: Type to filter the list of countries.':
		'Порада: Введіть текст для фільтрації списку країн.',
	'Search for a country:': 'Шукайте країну:',
	'Selection cancelled.': 'Вибір скасовано.',
	// Table demos
	'Available AI Models': 'Доступні AI моделі',
	'Table interaction finished.': 'Взаємодію з таблицею завершено.',
	'Type characters to see immediate filtering results.':
		'Введіть символи для миттєвої фільтрації результатів.',
	'Instant table interaction finished.': 'Миттєву взаємодію з таблицею завершено.',
	// Long list demo
	'Long List Demo – Scrolling Support': 'Демо довгого списку – Підтримка прокрутки',
	'Scroll through the 100 items:': 'Прогортайте через 100 елементів:',
	'No selection made.': 'Вибір не зроблено.',
	// Advanced form demo
	'Testing password masking and boolean fields.': 'Тестування маскування пароля та булевих полів.',
	Login: 'Логін',
	Password: 'Пароль',
	Phone: 'Телефон',
	'Remember me?': "Запам'ятати мене?",
	'Select your roles': 'Виберіть ваші ролі',
	Admin: 'Адміністратор',
	Editor: 'Редактор',
	Viewer: 'Глядач',
	'Form submitted!': 'Форму надіслано!',
	'Form data (password is hidden here):': 'Дані форми (пароль приховано):',
	// UiMessage demo
	'Form cancelled by user.': 'Форму скасовано користувачем.',
	'Must be 18+': 'Має бути 18+',
	'Favorite colour': 'Улюблений колір',
	// Countries
	Ukraine: 'Україна',
	'United States': 'Сполучені Штати',
	'United Kingdom': 'Великобританія',
	Germany: 'Німеччина',
	France: 'Франція',
	Italy: 'Італія',
	Spain: 'Іспанія',
	Canada: 'Канада',
	Australia: 'Австралія',
	Japan: 'Японія',
	China: 'Китай',
	Brazil: 'Бразилія',
	Poland: 'Польща',
	Netherlands: 'Нідерланди',
	Sweden: 'Швеція',
	Norway: 'Норвегія',
	Finland: 'Фінляндія',
	Denmark: 'Данія',
	// Table filter
	'Type to filter (or "::exit" to finish / "::clear" to reset):':
		'Введіть фільтр (або "::exit" для виходу / "::clear" для скидання):',
	// Multiselect instructions
	Instructions: 'Інструкції',
	'Highlight option': 'Підсвітити опцію',
	'Toggle selection': 'Вибрати/Зняти',
	'Toggle all': 'Вибрати всі',
	'Complete answer': 'Завершити вибір',
	'Instant Filter': 'Миттєвий фільтр',
	'Favorite color': 'Улюблений колір',
	'Age must be 18 or older': 'Вік має бути 18 або більше',
	'Username is required (supports Latin, Cyrillic, etc.)':
		"Ім'я обов'язкове (підтримується латиниця, кирилиця тощо)",
	'Invalid color': 'Невірний колір',
	Select: 'Виберіть',
	'Select Volume': 'Оберіть гучність',
	'Select Speed': 'Оберіть швидкість',
	'Select Reward': 'Оберіть винагороду',
	'Select Disk Size': "Оберіть об'єм диску",
	'View Components': 'Перегляд компонентів',
	'View Components Demo': 'Демо компонентів перегляду',
	'Nav Components': 'Навігаційні компоненти',
	'Navigation Components Demo': 'Демо навігаційних компонентів',
	'Tree View': 'Перегляд дерева',
	'Tree View Demo': 'Демо перегляду дерева',
	'Scenario 1: Select a File (Static Tree)': 'Сценарій 1: Вибір файлу (Статичне дерево)',
	'Select a file:': 'Оберіть файл:',
	'Scenario 2: Select a Directory (Async/Lazy)': 'Сценарій 2: Вибір папки (Асинхронно)',
	'Select a directory:': 'Оберіть папку:',
	'Scenario 3: Multi-Select Files': 'Сценарій 3: Мульти-вибір файлів',
	'Select files to delete:': 'Оберіть файли для видалення:',
	'Selected:': 'Обрано:',
	'You selected:': 'Ви обрали:',
	Selected: 'Обрано',
	items: "об'єктів",
	selected: 'обрано',
	'(empty)': '(порожньо)',
	'(loading...)': '(завантаження...)',
	'(Use arrow keys to navigate, Space to select, Enter to confirm)':
		'(Стрілки для навігації, Пробіл - обрати, Enter - підтвердити)',
	'(Use arrow keys to navigate, Enter to confirm)': '(Стрілки для навігації, Enter - обрати)',
	'Status:': 'Статус:',
	'Level:': 'Рівень:',
	Online: 'Онлайн',
	Offline: 'Офлайн',
	'Operation successful': 'Операція успішна',
	'System update available': 'Доступне оновлення системи',
	'Low disk space': 'Мало місця на диску',
	'Connection failed': "З'єднання розірвано",
	'This is a standard info alert.\nIt captures attention without being alarmist.':
		'Це стандартне інформаційне повідомлення.\nВоно привертає увагу без зайвої тривоги.',
	'Deployment completed successfully!\nAll tests passed.':
		'Розгортання успішно завершено!\nВсі тести пройдено.',
	'Great Success': 'Великий Успіх',
	'Dependencies are outdated.\nRun update to fix security issues.':
		'Залежності застаріли.\nЗапустіть оновлення для виправлення вразливостей.',
	'Security Warning': 'Попередження безпеки',
	'Critical system failure.\nUnable to connect to database.':
		"Критичний збій системи.\nНеможливо під'єднатися до бази даних.",
	'Fatal Error': 'Фатальна Помилка',
	'Press any key to continue...': 'Натисніть будь-яку клавішу...',
	'tree.empty': '(порожньо)',
	'tree.loading': '(завантаження...)',
	'tree.help.single': '(Стрілки для навігації, Enter - обрати)',
	'tree.help.multi': '(Стрілки для навігації, Пробіл - обрати, Enter - підтвердити)',
	'tree.selected': 'обрано',
	'Full path:': 'Повний шлях:',
	more: 'ще',
	BREADCRUMBS: 'ШЛЯХ (BREADCRUMBS)',
	Home: 'Головна',
	NanoWeb: 'NanoWeb',
	'UI-CLI': 'UI-CLI',
	Demos: 'Демо',
	Users: 'Користувачі',
	Admin: 'Адмін',
	Settings: 'Налаштування',
	TABS: 'ВКЛАДКИ (TABS)',
	General: 'Загальні',
	Profile: 'Профіль',
	Security: 'Безпека',
	Notifications: 'Сповіщення',
	'STEPS (WIZARD)': 'КРОКИ (WIZARD)',
	Cart: 'Кошик',
	Shipping: 'Доставка',
	Payment: 'Оплата',
	Review: 'Перевірка',
	BADGES: 'БЕЙДЖІ (BADGES)',
	Error: 'Помилка',
	TOASTS: 'ПОВІДОМЛЕННЯ (TOASTS)',
	ALERTS: 'СПОВІЩЕННЯ (ALERTS)',
	Info: 'Інфо',
	Warning: 'Увага',
	Green: 'Зелений',
	Blue: 'Синій',
	Red: 'Червоний',
	'table.filter_prompt': 'Фільтрувати таблицю',
	'Format must be:': 'Формат має бути:',
	yes: 'Так',
	no: 'Ні',
	'Object Form': "Форма об'єкта",
	'Object Map Form Demo – Premium UX': "Демо форми об'єкта – Premium UX",
	'Entering Object Map interface...': "Вхід в інтерфейс карти об'єкта...",
	'Data Saved:': 'Дані збережено:',
	'Editing cancelled.': 'Редагування скасовано.',
	Branch: 'Філіал',
	'Save and exit': 'Зберегти та вийти',
	'Cancel changes': 'Скасувати зміни',
	'Edit:': 'Редагування:',
	'Select field to edit:': 'Виберіть поле для редагування:',
	// V2 Components
	'V2 Components': 'V2 Компоненти',
	'This demo uses declarative functional components via render().':
		'Це демо використовує декларативні функціональні компоненти через render().',
	'New Architecture': 'Нова Архітектура',
	'What is your name?': 'Як вас звати?',
	Welcome: 'Ласкаво просимо',
	'Choose your role:': 'Оберіть вашу роль:',
	'Years of experience:': 'Років досвіду:',
	'Are you ready to build?': 'Ви готові будувати?',
	'Profile Created': 'Профіль створено',
	User: 'Користувач',
	Role: 'Роль',
	Exp: 'Досвід',
	years: 'років',
	Ready: 'Готово',
	Yes: 'Так',
	No: 'Ні',
	Developer: 'Розробник',
	Designer: 'Дизайнер',
	Manager: 'Менеджер',
	Production: 'Прод',
	Staging: 'Стейджинг',
	Development: 'Розробка',
	Logging: 'Логування',
	Caching: 'Кешування',
	Metrics: 'Метрики',
	USA: 'США',
	France: 'Франція',
	Germany: 'Німеччина',
	Japan: 'Японія',
	Ukraine: 'Україна',
	'--- V2 Components Showcase ---': '--- Презентація V2 Компонентів ---',
	'V2 Architecture Showcase': 'Презентація V2 Архітектури',
	'Demonstrating 100% of functional components in the new renderer engine.':
		'Демонстрація 100% функціональних компонентів у новому движку рендеринга.',
	MODULAR: 'МОДУЛЬНИЙ',
	'DEPENDENCY-FREE': 'БЕЗ ЗАЛЕЖНОСТЕЙ',
	'Engine initialized': 'Движок ініціалізовано',
	'Snapshot mode active': 'Режим снапшотів активний',
	'Initializing components...': 'Ініціалізація компонентів...',
	'Checking system state...': 'Перевірка стану системи...',
	'System Ready': 'Система Готова',
	'Navigation Views:': 'Навігаційні Види:',
	'Data Views (Static Table):': 'Перегляд Даних (Статична Таблиця):',
	'Component Registry': 'Регістр Компонентів',
	'Interactive Phase 1: Identity': 'Інтерактивна Фаза 1: Ідентифікація',
	'Enter username:': "Введіть ім'я користувача:",
	'Enter secret key:': 'Введіть секретний ключ:',
	'Enable telemetry:': 'Увімкнути телеметрію:',
	'Confirm deployment?': 'Підтвердити розгортання?',
	'Choose language / Оберіть мову:': 'Виберіть мову / Choose language:',
	'Format must be:': 'Формат має бути:',
	'Interactive Phase 2: Configuration': 'Інтерактивна Фаза 2: Конфігурація',
	'Select environment:': 'Виберіть оточення:',
	'Select features to enable:': 'Виберіть функції для активації:',
	'Enter country:': 'Введіть країну:',
	'Interactive Phase 3: Parameters': 'Інтерактивна Фаза 3: Параметри',
	'CPU Limit (%)': 'Ліміт CPU (%)',
	'Contact Phone:': 'Контактний телефон:',
	'Deploy Date:': 'Дата розгортання:',
	'Interactive Phase 4: File System': 'Інтерактивна Фаза 4: Файлова Система',
	'Select deploy target:': 'Виберіть ціль розгортання:',
	'Setup Complete': 'Налаштування Завершено',
	Env: 'Оточення',
	CPU: 'Процесор',
	Target: 'Ціль',
	Features: 'Функції',
	'Press any key to finish demonstration...':
		'Натисніть будь-яку клавішу для завершення демонстрації...',
	'validate.error': 'Помилка валідації',
	'Full Showcase': 'Повна демонстрація',
	'Select V2 Demo Scenario': 'Оберіть сценарій V2 демо',
	'hint.select': '(Стрілки для навігації. Enter для вибору)',
	'hint.multiselect': '(Пробіл - вибрати, Enter - завершити)',
	filter: 'Фільтр',
	none: 'немає',
	// Sortable
	'hint.sortable': '(↑/↓ — навігація, Пробіл — захопити, Enter — підтвердити)',
	'↑/↓': '↑/↓',
	Navigate: 'Навігація',
	Grab: 'Захопити',
	Confirm: 'Підтвердити',
	// Sortable demo
	Sortable: 'Сортування',
	'Sortable Demo': 'Демо сортування',
	'Reorder items using ↑/↓ to navigate, Space to grab, then ↑/↓ to move.':
		'Перетасуйте: ↑/↓ — навігація, Пробіл — захопити, потім ↑/↓ — перемістити.',
	'Scenario 1: Reorder priorities': 'Сценарій 1: Зміна пріоритетів',
	'Set priority order:': 'Встановіть порядок пріоритетів:',
	Critical: 'Критичний',
	High: 'Високий',
	Medium: 'Середній',
	Low: 'Низький',
	'Final order:': 'Фінальний порядок:',
	// Form array builder
	'Add new item': 'Додати новий елемент',
	Done: 'Готово',
	'Action: ': 'Дія: ',
	Value: 'Значення',
	Edit: 'Редагувати',
	Delete: 'Видалити',
	Back: 'Назад',
	// Sandbox UI
	'Select a component to test:': 'Оберіть компонент для тесту:',
	'Exiting Sandbox. 👋': 'Вихід з Пісочниці. 👋',
	'[Variant]': '[Варіант]',
	'+ Create New Variant': '+ Створити Новий Варіант',
	'← Back to Components': '← Назад до Компонентів',
	'Choose variation:': 'Оберіть варіацію:',
	'Enter new variant name:': 'Введіть назву нового варіанту:',
	'▶ Run Prompt (Test)': '▶ Запустити Інтерактив (Test)',
	'↺ Reset to Defaults': '↺ Скинути до Стандартних',
	'✖ Delete Variant': '✖ Видалити Варіант',
	'← Back': '← Назад',
}
