export const renderers: Map<string, (data: any) => string>;
export default CLIInputAdapter;
import CLIInputAdapter from './InputAdapter.js';
import { CancelError } from '@nan0web/ui/core';
import { createInput } from './ui/index.js';
import { ask } from './ui/index.js';
import { Input } from './ui/index.js';
import { select } from './ui/index.js';
import { next } from './ui/index.js';
import { pause } from './ui/index.js';
export { CLIInputAdapter, CancelError, createInput, ask, Input, select, next, pause };
